### ISSUE TITLE
Click on "Sign in" has no effect

### ISSUE THREAD

**Issue by drzraf** [geeks-r-us/anbox-playstore-installer#59]
When running the Play Store the first (after having granted it and Play Services all possible permissions), I click "Sign in".

It has no effect and I see the following in `logcat`:

```
12-20 23:46:35.681   110  1410 I art     : Thread[81,tid=1410,Runnable,Thread*=0x7f6050923800,peer=0x12f1fb80,"SoundPoolListenerThread"] setPriority(PRIO_PROCESS, 1410, 0) failed: Permission denied
12-20 23:46:35.699    40    93 I MediaPlayerService: MediaPlayerService::getOMX
12-20 23:46:35.699   110  1411 I OMXClient: MuxOMX ctor
12-20 23:46:35.700   110  1411 E ACodec  : Unable to instantiate a decoder for type 'audio/vorbis' with err 0xfffffffe.
12-20 23:46:35.700   110  1411 E ACodec  : signalError(omxError 0xfffffffe, internalError -2)
12-20 23:46:35.700   110  1411 E MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
12-20 23:46:35.700   110  1409 E SoundPool: Unable to load sample
12-20 23:46:35.701   110   170 W AudioService: onLoadSoundEffects(), Error -2147483648 while loading samples
12-20 23:46:35.715    40    93 I MediaPlayerService: MediaPlayerService::getOMX
12-20 23:46:35.716   110  1412 I OMXClient: MuxOMX ctor
12-20 23:46:35.716   110  1412 E ACodec  : Unable to instantiate a decoder for type 'audio/vorbis' with err 0xfffffffe.
12-20 23:46:35.716   110  1412 E ACodec  : signalError(omxError 0xfffffffe, internalError -2)
12-20 23:46:35.716   110  1412 E MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
12-20 23:46:35.717   110  1409 E SoundPool: Unable to load sample
12-20 23:46:35.742  1368  1368 I MultiDex: VM with version 2.1.0 has multidex support
12-20 23:46:35.742  1368  1368 I MultiDex: Installing application
12-20 23:46:35.748  1368  1368 I MultiDex: MultiDexExtractor(204713000, /data/app/com.google.android.gms-1/base.apk, /data/user/0/com.google.android.gms/code_cache/secondary-dexes)
12-20 23:46:35.750  1368  1368 I MultiDex: Blocking on lock /data/user/0/com.google.android.gms/code_cache/secondary-dexes/MultiDex.lock
12-20 23:46:35.750  1368  1368 I MultiDex: /data/user/0/com.google.android.gms/code_cache/secondary-dexes/MultiDex.lock locked
12-20 23:46:35.750  1368  1368 I MultiDex: MultiDexExtractor.load(204713000, /data/app/com.google.android.gms-1/base.apk, false, )
12-20 23:46:35.752  1368  1368 I MultiDex: loading existing secondary dex files
12-20 23:46:35.753  1368  1368 I MultiDex: load found 5 secondary dex files
12-20 23:46:35.753  1368  1368 W MultiDex: Failed to find method makeDexElements, will check alternate overload:Method makeDexElements with parameters [class java.util.ArrayList, class java.io.File, class java.util.ArrayList] not found in class dalvik.system.DexPathList
12-20 23:46:35.754  1368  1368 E MultiDex: MultiDex installation failure
12-20 23:46:35.754  1368  1368 E MultiDex: java.lang.NoSuchMethodException: Method makeDexElements with parameters [class java.util.ArrayList, class java.io.File, class java.util.ArrayList, class java.lang.ClassLoader] not found in class dalvik.system.DexPathList
12-20 23:46:35.754  1368  1368 E MultiDex: 	at dd.c(:com.google.android.gms@204713000@20.47.13 (000300-344095733):4)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at dd.e(:com.google.android.gms@204713000@20.47.13 (000300-344095733):7)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at dd.d(:com.google.android.gms@204713000@20.47.13 (000300-344095733):25)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at nev.attachBaseContext(:com.google.android.gms@204713000@20.47.13 (000300-344095733):37)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at android.app.Application.attach(Application.java:189)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at android.app.Instrumentation.newApplication(Instrumentation.java:992)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3188)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at android.os.Looper.loop(Looper.java:154)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at java.lang.reflect.Method.invoke(Native Method)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
12-20 23:46:35.754  1368  1368 E MultiDex: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
12-20 23:46:35.759  1368  1368 I MultiDex: Installing application
12-20 23:46:35.759  1368  1368 I MultiDex: install done
12-20 23:46:35.781  1368  1368 I GmsApplication: Staging modules and/or updating config
12-20 23:46:35.789  1368  1368 E ChimeraCfgMgr: Failed to read module config: java.io.FileNotFoundException: /data/data/com.google.android.gms/app_chimera/current_config.fb (No such file or directory)
12-20 23:46:35.789  1368  1368 I GmsApplication: Updating config
12-20 23:46:35.794  1368  1368 W FileUtils: Failed to set world readable: /data/data/com.google.android.gms/app_chimera/current_config.fb
12-20 23:46:35.795  1368  1368 E ChimeraCfgMgr: Failed to read module config: java.io.FileNotFoundException: /data/data/com.google.android.gms/app_chimera/current_config.fb (No such file or directory)
12-20 23:46:35.830  1368  1368 I GmsModuleFndr: Beginning GMS chimera module scan
12-20 23:46:35.836  1368  1368 E DynamiteModule: Failed to load IDynamiteLoader from GmsCore: Didn't find class "com.google.android.gms.chimera.container.DynamiteLoaderImpl$GmsProcessDynamiteLoaderImpl" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/data/app/com.google.android.gms-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-1/lib/arm, /data/app/com.google.android.gms-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
12-20 23:46:35.836  1368  1368 I DynamiteModule: Considering local module com.google.android.gms.googlecertificates:6 and remote module com.google.android.gms.googlecertificates:0
12-20 23:46:35.836  1368  1368 I DynamiteModule: Selected local version of com.google.android.gms.googlecertificates
12-20 23:46:35.841  1368  1368 E ChimeraCfgMgr: Failed to read module config: java.io.FileNotFoundException: /data/data/com.google.android.gms/app_chimera/current_config.fb (No such file or directory)
12-20 23:46:35.851  1368  1368 I ModuleSetMgr: Computing pending module set with APKs: []
12-20 23:46:35.854  1368  1368 I ModuleSetMgr: Container features not yet downloaded are disabled.
12-20 23:46:35.862  1368  1368 I ModuleSetMgr: Pending container module APKs: []
12-20 23:46:35.862  1368  1368 I ModuleSetMgr: Pending non-container module APKs: []
12-20 23:46:35.865  1368  1368 D AndroidRuntime: Shutting down VM
12-20 23:46:35.867  1368  1368 E ChimeraCfgMgr: Failed to read module config: java.io.FileNotFoundException: /data/data/com.google.android.gms/app_chimera/current_config.fb (No such file or directory)
12-20 23:46:35.867  1368  1368 W ChimeraUtils: Can't get Chimera config
12-20 23:46:35.869  1368  1368 E AndroidRuntime: FATAL EXCEPTION: main
12-20 23:46:35.869  1368  1368 E AndroidRuntime: Process: com.google.process.gapps, PID: 1368
12-20 23:46:35.869  1368  1368 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lbgkg;
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at bgkh.<init>(:com.google.android.gms@204713000@20.47.13 (000300-344095733):2)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at bgkm.h(:com.google.android.gms@204713000@20.47.13 (000300-344095733):0)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at bggd.iterator(:com.google.android.gms@204713000@20.47.13 (000300-344095733):0)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at maq.g(:com.google.android.gms@204713000@20.47.13 (000300-344095733):60)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at maq.n(:com.google.android.gms@204713000@20.47.13 (000300-344095733):2)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at maq.j(:com.google.android.gms@204713000@20.47.13 (000300-344095733):18)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at maq.c(:com.google.android.gms@204713000@20.47.13 (000300-344095733):0)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at nev.b(:com.google.android.gms@204713000@20.47.13 (000300-344095733):22)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at nev.attachBaseContext(:com.google.android.gms@204713000@20.47.13 (000300-344095733):47)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at android.app.Application.attach(Application.java:189)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:992)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3188)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "bgkg" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/data/app/com.google.android.gms-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-1/lib/arm, /data/app/com.google.android.gms-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
12-20 23:46:35.869  1368  1368 E AndroidRuntime: 	... 22 more
12-20 23:46:35.880   110   124 W BroadcastQueue: Unable to launch app com.google.android.gms/10051 for broadcast Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) }: process is bad
12-20 23:46:35.880   110   124 W BroadcastQueue: Unable to launch app com.google.android.gms/10051 for broadcast Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) }: process is bad
12-20 23:46:35.901  1368  1373 I art     : Do partial code cache collection, code=26KB, data=21KB
12-20 23:46:35.901  1368  1373 I art     : After code cache collection, code=26KB, data=21KB
12-20 23:46:35.901  1368  1373 I art     : Increasing code cache capacity to 128KB
12-20 23:46:35.914   110   485 I OpenGLRenderer: Initialized EGL, version 1.4
12-20 23:46:35.914   110   485 D OpenGLRenderer: Swap behavior 1
12-20 23:46:36.107   110   124 W BroadcastQueue: Unable to launch app com.google.android.gms/10051 for broadcast Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) }: process is bad
12-20 23:46:36.108   110   124 W BroadcastQueue: Unable to launch app com.google.android.gms/10051 for broadcast Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) }: process is bad
```

**Comment by drzraf** [comment]
Got this when trying to run another app' too.

**Comment by JonTabor** [comment]
This is ancient, but I noticed it's still open.  As found in other issues for the same thing, the key is to make sure Google Play and Google Play Services have the correct permissions (basically...all of them).
