### ISSUE TITLE
Missing permission groups

### ISSUE THREAD

**Issue by glenfordwilliams** [geeks-r-us/anbox-playstore-installer#72]
Not sure if i should report here but after installed houdini using the script provided i was able to get whatsapp working however when i gets to point of sending the OTP it fails.

adb outputs the following

```
09-22 08:02:40.646   108   226 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@5518cad attribute=null, token = android.os.BinderProxy@f335b8
09-22 08:02:40.649  3105  3105 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.auth.api.phone.service.SmsRetrieverApiService.START pkg=com.google.android.gms }
09-22 08:02:40.649  3105  3105 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.auth.api.phone.service.SmsRetrieverApiService.START pkg=com.google.android.gms }
09-22 08:02:40.674  3105  3307 W PermCheckPreProcessor: API 126 requires missing permission groups: [android.permission-group.SMS]
09-22 08:02:40.682  4371  4485 E GoogleApiAvailability: Unexpected error code 19
09-22 08:02:45.684  3105  3105 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.auth.api.phone.service.SmsRetrieverApiService.START pkg=com.google.android.gms }
```

**Comment by geeks-r-us** [comment]
That looks like that whatsapp is lagging the permission to access sms.
anbox does not have installed messages and this script ether does not install it due to the lag of hardware / emulation. 
Thats probably why the group does no exist.

Fix could be to install messages and the required dependencies

**Comment by JoseskVolpe** [comment]
I get the following stacktrace:

```
03-28 07:41:23.513   634   647 W PermCheckPreProcessor: API 126 requires missing permission groups: [android.permission-group.SMS]
03-28 07:41:23.518   689  1797 W GoogleApiAvailability: GMS core API Availability. ConnectionResult=19, tag=null
03-28 07:41:23.518   689  1797 W GoogleApiAvailability: java.lang.IllegalArgumentException
03-28 07:41:23.518   689  1797 W GoogleApiAvailability:         at X.0WT.A06(:138707)
03-28 07:41:23.518   689  1797 W GoogleApiAvailability:         at X.1pG.A06(:278659)
03-28 07:41:23.518   689  1797 W GoogleApiAvailability:         at X.01u.A07(:4017)
03-28 07:41:23.518   689  1797 W GoogleApiAvailability:         at X.01u.onConnectionFailed(:4116)
03-28 07:41:23.518   689  1797 W GoogleApiAvailability:         at X.15f.A01(:215616)
03-28 07:41:23.518   689  1797 W GoogleApiAvailability:         at X.170.handleMessage(:216661)
03-28 07:41:23.518   689  1797 W GoogleApiAvailability:         at android.os.Handler.dispatchMessage(Handler.java:102)
03-28 07:41:23.518   689  1797 W GoogleApiAvailability:         at android.os.Looper.loop(Looper.java:154)
03-28 07:41:23.518   689  1797 W GoogleApiAvailability:         at android.os.HandlerThread.run(HandlerThread.java:61)
```

After inserting my phone number and confirming it, nothing occurs. Making adb logcat i can see this error result.

Edit: It occurs on a OpenGApps installed IMG, using a IMG without OpenGApps is a workaround
